In [ ]:
import torch
print(torch.__version__)

2.11.0+cu128


In [ ]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is available!
Using GPU: Tesla T4


# **Creating** **a** **Tensor**

In [ ]:
# using empty
a = torch.empty(2,3)

In [ ]:
# check type
type(a)

torch.Tensor

In [ ]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# using rand
torch.rand(2,3)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [ ]:
# use of seed
torch.rand(2,3)

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

In [ ]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

# **Other** **ways**

In [ ]:
# arange
print("using arange ->", torch.arange(0,10,2))

using arange -> tensor([0, 2, 4, 6, 8])


In [ ]:
# using linspace
print("using linspace ->", torch.linspace(0,10,10))

using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])


In [ ]:
# using eye
print("using eye ->", torch.eye(5))

using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [ ]:
# using full
print("using full ->", torch.full((3, 3), 5))

using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


# **Tensor Shapes**

# **Tensor Data Types**

In [ ]:
# find data type
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.dtype

torch.int64

In [ ]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
# using to()
x
print(x)
x.to(torch.float32)

tensor([[1, 2, 3],
        [4, 5, 6]])


tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


# **Mathematical operations**

1. Scalar operation

In [ ]:
x = torch.rand(2,2)
x

tensor([[0.2627, 0.0428],
        [0.2080, 0.1180]])

In [ ]:
# addition
x + 2


tensor([[2.2627, 2.0428],
        [2.2080, 2.1180]])

In [ ]:
# substraction
x - 2

tensor([[-1.7373, -1.9572],
        [-1.7920, -1.8820]])

In [ ]:
# multiplication
x * 3

tensor([[0.7881, 0.1285],
        [0.6241, 0.3541]])

In [ ]:
# division
x / 3

tensor([[0.0876, 0.0143],
        [0.0693, 0.0393]])

In [ ]:
# int division
(x * 100)//3

tensor([[8., 1.],
        [6., 3.]])

In [ ]:
# mod
((x * 100)//3)%2

tensor([[0., 1.],
        [0., 1.]])

In [ ]:
# power
x**2

tensor([[0.0690, 0.0018],
        [0.0433, 0.0139]])

2. Element wise operation

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.1217, 0.7356, 0.7118],
        [0.7876, 0.4183, 0.9014]])
tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])


In [ ]:
# add
a + b

tensor([[1.1186, 1.4921, 0.9357],
        [1.0899, 0.5967, 1.7253]])

In [ ]:
# sub
a - b

tensor([[-0.8752, -0.0209,  0.4879],
        [ 0.4852,  0.2399,  0.0776]])

In [ ]:
# multiply
a * b

tensor([[0.1213, 0.5565, 0.1594],
        [0.2381, 0.0746, 0.7426]])

In [ ]:
# division
a / b

tensor([[0.1221, 0.9724, 3.1790],
        [2.6049, 2.3445, 1.0942]])

In [ ]:
# power
a ** b

tensor([[0.1225, 0.7927, 0.9267],
        [0.9303, 0.8560, 0.9180]])

In [ ]:
# mod
a % b

tensor([[0.1217, 0.7356, 0.0401],
        [0.1829, 0.0615, 0.0776]])

In [ ]:
c = torch.tensor([1, -2, 3, -4])

In [ ]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [ ]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [ ]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [ ]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [ ]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

# 3. Reduction operation

In [ ]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e


tensor([[4., 6., 0.],
        [1., 9., 9.]])

In [ ]:
# sum
torch.sum(e)


tensor(29.)

In [ ]:
# sum along columns
torch.sum(e, dim=0)


tensor([ 5., 15.,  9.])

In [ ]:

# sum along rows
torch.sum(e, dim=1)

tensor([10., 19.])

In [ ]:
# mean
torch.mean(e)


tensor(4.8333)

In [ ]:
# mean along col
torch.mean(e, dim=0)

tensor([2.5000, 7.5000, 4.5000])

In [ ]:
# median
torch.median(e)

tensor(4.)

In [ ]:
# max and min
torch.max(e)


tensor(9.)

In [ ]:
torch.min(e)

tensor(0.)

In [ ]:
# product
torch.prod(e)

tensor(0.)

In [ ]:
# standard deviation
torch.std(e)

tensor(3.8687)

In [ ]:
# variance
torch.var(e)

tensor(14.9667)

In [ ]:
# argmax
torch.argmax(e)

tensor(4)

In [ ]:
# argmin
torch.argmin(e)

tensor(2)

# 4. Matrix operations

In [ ]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[8, 0, 7],
        [0, 0, 9]])
tensor([[5, 7],
        [3, 9],
        [4, 0]])


In [ ]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[68, 56],
        [36,  0]])

In [ ]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [ ]:
# transpose
torch.transpose(f, 0, 1)

tensor([[8, 0],
        [0, 0],
        [7, 9]])

In [ ]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[5., 7., 5.],
        [9., 9., 7.],
        [5., 9., 8.]])

In [ ]:
# determinant
torch.det(h)

tensor(-34.0000)

In [ ]:
# inverse
torch.inverse(h)

tensor([[-0.2647,  0.3235, -0.1176],
        [ 1.0882, -0.4412, -0.2941],
        [-1.0588,  0.2941,  0.5294]])

# 5. Comparison operations

In [ ]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[9, 7, 9],
        [2, 6, 7]])
tensor([[7, 8, 3],
        [6, 1, 5]])


In [ ]:
# greater than
i > j


tensor([[ True, False,  True],
        [False,  True,  True]])

In [ ]:
# less than
i < j


tensor([[False,  True, False],
        [ True, False, False]])

In [ ]:

# equal to
i == j


tensor([[False, False, False],
        [False, False, False]])

In [ ]:
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[True, True, True],
        [True, True, True]])

# 6. Special functions

In [ ]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[5., 0., 4.],
        [3., 8., 8.]])

In [ ]:
# log
torch.log(k)

tensor([[1.6094,   -inf, 1.3863],
        [1.0986, 2.0794, 2.0794]])

In [ ]:
# exp
torch.exp(k)

tensor([[1.4841e+02, 1.0000e+00, 5.4598e+01],
        [2.0086e+01, 2.9810e+03, 2.9810e+03]])

In [ ]:
# sqrt
torch.sqrt(k)

tensor([[2.2361, 0.0000, 2.0000],
        [1.7321, 2.8284, 2.8284]])

In [ ]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9933, 0.5000, 0.9820],
        [0.9526, 0.9997, 0.9997]])

In [ ]:
# softmax
torch.softmax(k, dim=0)

tensor([[8.8080e-01, 3.3535e-04, 1.7986e-02],
        [1.1920e-01, 9.9966e-01, 9.8201e-01]])

In [ ]:
# relu
torch.relu(k)

tensor([[5., 0., 4.],
        [3., 8., 8.]])

# Inplace Operations

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.6179, 0.3379, 0.2170],
        [0.9454, 0.7116, 0.1157]])
tensor([[0.6574, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])


In [ ]:
m.add_(n)

tensor([[1.2752, 0.6830, 0.2624],
        [1.9251, 1.2663, 0.8025]])

In [ ]:
m

tensor([[1.2752, 0.6830, 0.2624],
        [1.9251, 1.2663, 0.8025]])

In [ ]:
n

tensor([[0.6574, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])

In [ ]:
torch.relu(m)

tensor([[1.2752, 0.6830, 0.2624],
        [1.9251, 1.2663, 0.8025]])

In [ ]:
m.relu_()

tensor([[1.2752, 0.6830, 0.2624],
        [1.9251, 1.2663, 0.8025]])

In [ ]:
m

tensor([[1.2752, 0.6830, 0.2624],
        [1.9251, 1.2663, 0.8025]])

# Copying a Tensor

In [ ]:
a = torch.rand(2,3)
a

tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])

In [ ]:
b = a

In [ ]:
b

tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])

In [ ]:
a[0][0] = 0

In [ ]:
a

tensor([[0.0000, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])

In [ ]:
b

tensor([[0.0000, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])

In [ ]:
id(a)

138056253572272

In [ ]:
id(b)

138056253572272

In [ ]:
b = a.clone()

In [ ]:
a

tensor([[0.0000, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])

In [ ]:
b

tensor([[0.0000, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])

In [ ]:
a[0][0] = 10

In [ ]:
a

tensor([[10.0000,  0.0748,  0.9605],
        [ 0.3271,  0.0103,  0.9516]])

In [ ]:
b

tensor([[0.0000, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])

In [ ]:
id(a)

138056253572272

In [ ]:
id(b)

138056253485888

# Tensor Operations on **GPU**  

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = torch.device('cuda')

In [ ]:
# create a new tensor on GPU
torch.rand((2,3), device = device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [ ]:
# moving an existing tenor to GPU
# this tansor on CPU
a = torch.rand(2,3)
a

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [ ]:
# Now move to the GPU
b = a.to(device)
b

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]], device='cuda:0')

In [ ]:
b+5

tensor([[5.2855, 5.2324, 5.9141],
        [5.7668, 5.1659, 5.4393]], device='cuda:0')

🔥 What this code shows

- CPU vs GPU performance

- Matrix multiplication speed

- Why tensors + GPU are powerful

In [ ]:
import torch
import time

# Define the size of the matrices
size = 10000  # Large size for performance comparison

# Create random matrices on CPU
matrix_cpu1 = torch.randn(size, size)
matrix_cpu2 = torch.randn(size, size)

# Measure time on CPU
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)  # Matrix multiplication on CPU
cpu_time = time.time() - start_time

print(f"Time on CPU: {cpu_time:.4f} seconds")

# Move matrices to GPU
matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')

# Measure time on GPU
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)  # Matrix multiplication on GPU
torch.cuda.synchronize()  # Ensure all GPU operations are complete
gpu_time = time.time() - start_time

print(f"Time on GPU: {gpu_time:.4f} seconds")

# Compare results
print("\nSpeedup (CPU time / GPU time):", cpu_time / gpu_time)

Time on CPU: 15.5964 seconds
Time on GPU: 0.6565 seconds

Speedup (CPU time / GPU time): 23.758475501175464


# **Reshaping** **Tensors**

In [ ]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
b = torch.rand(2,3,4)
b

tensor([[[0.3932, 0.7483, 0.7985, 0.4626],
         [0.9414, 0.5752, 0.8881, 0.7989],
         [0.9514, 0.0141, 0.8903, 0.1649]],

        [[0.3162, 0.1331, 0.6763, 0.4254],
         [0.2375, 0.5430, 0.1174, 0.6532],
         [0.5115, 0.3094, 0.7907, 0.7351]]])

In [ ]:
# permute
b.permute(2,1,0)

tensor([[[0.3932, 0.3162],
         [0.9414, 0.2375],
         [0.9514, 0.5115]],

        [[0.7483, 0.1331],
         [0.5752, 0.5430],
         [0.0141, 0.3094]],

        [[0.7985, 0.6763],
         [0.8881, 0.1174],
         [0.8903, 0.7907]],

        [[0.4626, 0.4254],
         [0.7989, 0.6532],
         [0.1649, 0.7351]]])

In [ ]:
# permute
b.permute(2,1,0).shape

torch.Size([4, 3, 2])

In [ ]:
# unsqueeze
# image size
c = torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [ ]:
# squeeze
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

# NumPy and **PyTorch**

In [ ]:
import numpy as np


Tensor to **NumPy**

In [ ]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [ ]:
b = a.numpy()

In [ ]:
b

array([1, 2, 3])

In [ ]:
type(b)

numpy.ndarray

NumPy  to   Tensor

In [ ]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [ ]:
torch.from_numpy(c)

tensor([1, 2, 3])